#!/bin/bash
python condense.py ny-nyc-00.txt condense/ny-nyc-00.txt
python condense.py ny-nyc-01.txt condense/ny-nyc-01.txt
python condense.py ny-nyc-02.txt condense/ny-nyc-02.txt
python condense.py ny-nyc-03.txt condense/ny-nyc-03.txt
python condense.py ny-nyc-04.txt condense/ny-nyc-04.txt
python condense.py ny-nyc-05.txt condense/ny-nyc-05.txt
python condense.py ny-nyc-06.txt condense/ny-nyc-06.txt
python condense.py ny-nyc-07.txt condense/ny-nyc-07.txt
python condense.py ny-nyc-08.txt condense/ny-nyc-08.txt
python condense.py ny-nyc-09.txt condense/ny-nyc-09.txt
python condense.py ny-nyc-10.txt condense/ny-nyc-10.txt
python condense.py ny-nyc-11.txt condense/ny-nyc-11.txt
python condense.py ny-nyc-12.txt condense/ny-nyc-12.txt
python condense.py ny-nyc-13.txt condense/ny-nyc-13.txt
python condense.py ny-nyc-14.txt condense/ny-nyc-14.txt
python condense.py ny-nyc-15.txt condense/ny-nyc-15.txt
python condense.py ny-nyc-16.txt condense/ny-nyc-16.txt
python condense.py ny-nyc-17.txt condense/ny-nyc-17.txt
python condense.py ny-nyc-18.txt condense/ny-nyc-18.txt
python condense.py ny-nyc-19.txt condense/ny-nyc-19.txt
python condense.py ny-nyc-20.txt condense/ny-nyc-20.txt
python condense.py ny-nyc-21.txt condense/ny-nyc-21.txt
python condense.py ny-nyc-22.txt condense/ny-nyc-22.txt
python condense.py ny-nyc-23.txt condense/ny-nyc-23.txt
python condense.py ny-nyc-24.txt condense/ny-nyc-24.txt
python condense.py ny-nyc-25.txt condense/ny-nyc-25.txt
python condense.py ny-nyc-26.txt condense/ny-nyc-26.txt
python condense.py ny-nyc-27.txt condense/ny-nyc-27.txt
python condense.py ny-nyc-28.txt condense/ny-nyc-28.txt
python condense.py ny-nyc-29.txt condense/ny-nyc-29.txt
python condense.py ny-nyc-30.txt condense/ny-nyc-30.txt
python condense.py ny-nyc-31.txt condense/ny-nyc-31.txt
python condense.py ny-nyc-32.txt condense/ny-nyc-32.txt
python condense.py ny-nyc-33.txt condense/ny-nyc-33.txt
python condense.py ny-nyc-34.txt condense/ny-nyc-34.txt
python condense.py ny-nyc-35.txt condense/ny-nyc-35.txt
python condense.py ny-nyc-36.txt condense/ny-nyc-36.txt
python condense.py ny-nyc-37.txt condense/ny-nyc-37.txt
python condense.py ny-nyc-38.txt condense/ny-nyc-38.txt
python condense.py ny-nyc-39.txt condense/ny-nyc-39.txt
python condense.py ny-nyc-40.txt condense/ny-nyc-40.txt
python condense.py ny-nyc-41.txt condense/ny-nyc-41.txt
python condense.py ny-nyc-42.txt condense/ny-nyc-42.txt
python condense.py ny-nyc-43.txt condense/ny-nyc-43.txt
python condense.py ny-nyc-44.txt condense/ny-nyc-44.txt
python condense.py ny-nyc-45.txt condense/ny-nyc-45.txt
python condense.py ny-nyc-46.txt condense/ny-nyc-46.txt
python condense.py ny-nyc-47.txt condense/ny-nyc-47.txt
python condense.py ny-nyc-48.txt condense/ny-nyc-48.txt
python condense.py ny-nyc-49.txt condense/ny-nyc-49.txt
python condense.py ny-nyc-50.txt condense/ny-nyc-50.txt
python condense.py ny-nyc-51.txt condense/ny-nyc-51.txt
python condense.py ny-nyc-52.txt condense/ny-nyc-52.txt
