#!/bin/bash
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-00.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-00.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-01.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-01.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-02.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-02.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-03.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-03.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-04.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-04.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-05.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-05.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-06.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-06.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-07.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-07.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-08.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-08.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-09.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-09.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-10.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-10.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-11.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-11.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-12.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-12.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-13.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-13.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-14.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-14.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-15.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-15.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-16.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-16.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-17.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-17.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-18.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-18.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-19.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-19.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-20.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-20.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-21.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-21.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-22.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-22.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-23.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-23.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-24.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-24.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-25.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-25.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-26.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-26.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-27.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-27.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-28.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-28.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-29.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-29.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-30.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-30.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-31.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-31.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-32.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-32.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-33.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-33.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-34.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-34.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-35.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-35.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-36.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-36.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-37.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-37.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-38.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-38.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-39.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-39.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-40.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-40.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-41.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-41.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-42.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-42.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-43.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-43.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-44.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-44.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-45.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-45.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-46.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-46.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-47.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-47.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-48.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-48.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-49.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-49.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-50.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-50.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-51.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-51.txt
python loc_bucket.py /lfs/madmax7/0/ramasshe/xdata/output/condense/ny-nyc-52.txt /lfs/madmax7/0/ramasshe/xdata/output/loc_bucket/ny-nyc-52.txt
